### ISSUE TITLE
배포하기 - github actions로 배포하기

### ISSUE THREAD

**Issue by createhb21** [createhb21/monorepo-setting#10]
# 배포하기 - github actions로 배포하기
- [ ] `.github` 폴더에 2개의 `yml` 파일을 만든다.
- [ ] `.github/actions/yarn-install/action.yml` (Composite action)
  -  yarn install 공통으로 사용하는 action을 만들기
- [ ] `.github/workflows/ci-wanted-app.yml`
  - apps/wanted 프로젝트를 빌드/배포 하는 파일

**`.github/actions/yarn-install/action.yml`**
```
name: 'Monorepo install (yarn)'
description: 'Run yarn install'

runs:
  using: 'composite'

  steps:
    - name: Expose yarn config as "$GITHUB_OUTPUT"
      id: yarn-config
      shell: bash
      run: |
        echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore yarn cache
      uses: actions/cache@v3
      id: yarn-download-cache
      with:
        path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
        key: yarn-download-cache-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-download-cache-

    - name: Restore yarn install state
      id: yarn-install-state-cache
      uses: actions/cache@v3
      with:
        path: .yarn/ci-cache/
        key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}

    - name: Install dependencies
      shell: bash
      run: |
        yarn install --immutable --inline-builds
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
        YARN_INSTALL_STATE_PATH: .yarn/ci-cache/install-state.gz # Very small speedup when lock does not change
```

**`.github/workflows/ci-wanted-app.yml`**
```
name: CI-wanted-app

on:
  push:
    branches:
      - 6-deploy-github-actions
    paths:
      - 'apps/wanted/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-install

      - name: Build web-app
        working-directory: apps/wanted
        run: |
          yarn build
```

## 한개 yml 파일로 선택하여 배포해 보기.
- [ ] `.github/workflows`에 `ci-deploy-manual.yml` 생성
ci-deploy-manual.yml에 아래 내용을 넣는다.
```
name: CI-deploy-manual

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: '배포할 서비스명을 선택해주세요.'
        required: true
        default: 'wanted'
        type: choice
        options:
          - wanted
          - admin

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-install

      - name: Build web-app
        working-directory: apps/${{ inputs.service_name }}
        run: |
          yarn build
```
**commit 후 push**
1. github 레포에서 actions 탭 --> CI-deploy-manual 클릭
2. Run workflow 버튼 눌러서 추가된 내용 확인 

# 빵 부스러기
**composite actions이란?**
- [GitHub Actions의 Composite 액션 작성하기](https://blog.outsider.ne.kr/1592)
- [카카오웹툰은 GitHub Actions를 어떻게 사용하고 있을까?](https://fe-developers.kakaoent.com/2022/220106-github-actions/)
